### ISSUE TITLE
NOT FIND TEST DATASET

### ISSUE THREAD

**Issue by FDwuyun** [huhanwj/P2SLAM-sim#1]
May I ask if you can provide test data? I have filled out several forms for the P2SLAM dataset, but have not received any response.

**Comment by huhanwj** [comment]
Hi, please try to email the authors of P2SLAM listed on their [website](https://wcsng.ucsd.edu/p2slam/) if you encounter any trouble downloading the data. 

I could not provide the data as I do not have the copyright, also this repo is for a course project and I have not touched this field for quite a long time. So I guess nothing I can help here.

A friendly reminder is that they may be slow on response, just be patient if you do not have a deadline.
